#!/usr/bin/env bash

SCRIPT=$1

INPUT="${TMP:-/tmp}/output_in$$"
CHANGES="${TMP:-/tmp}/output_ch$$"
trap "exit 1" HUP INT QUIT PIPE TERM
trap "rm -f ${INPUT} ${CHANGES}" EXIT

# collect input
cat > "${INPUT}"

cat "${SCRIPT}"| awk '/^\.R/ { exit } ; { print }' > "${CHANGES}"

# ensure there is input
if test -s "${INPUT}"; then
  # ensure there is a script
  if test -s "${CHANGES}"; then
    # establish location of stanford-tregex.jar
    TREGEX="$(tregex_location)"
    # run tsurgeon
    timeout 20s java -mx300m -cp "${TREGEX}" edu.stanford.nlp.trees.tregex.tsurgeon.Tsurgeon -treeFile "${INPUT}" "${CHANGES}" -s
  # simple cat when no script
  else
    cat "${INPUT}"
  fi
fi

